using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewModdingAPI.Utilities;
using StardewValley;
using StardewValley.Menus;
using StardewValley.Monsters;
using StardewValley.Network;
using StardewValley.TerrainFeatures;
using Harmony;

namespace FarmTypeManager
{
    public partial class ModEntry : Mod
    {
        public class HarmonyPatch_SpawnedMineralCollection
        {
            /// <summary>Applies this Harmony patch to the game through the provided instance.</summary>
            /// <param name="harmony">This mod's Harmony instance.</param>
            public static void ApplyPatch(HarmonyInstance harmony)
            {
                harmony.Patch(
                    original: AccessTools.Method(typeof(Farmer), nameof(Farmer.addItemToInventoryBool), new[] { typeof(Item), typeof(bool) }), //original method: Farmer.addItemToInventoryBool(Item, bool)
                    prefix: new HarmonyMethod(typeof(HarmonyPatch_SpawnedMineralCollection), nameof(addItemToInventoryBool_Prefix)) //prefix method: addItemToInventoryBool_Prefix
                );
            }

            /// <summary>Updates the local player's collection menu when they pick up a new mineral.</summary>
            /// <remarks>This imitates the check performed in the original method, but targets minerals instead of gems.
            /// As of SDV 1.4.5, the original code only adds minerals to the collection when they are generated by the <see cref="GeodeMenu"/>.</remarks>
            /// <param name="item"></param>
            /// <param name="makeActiveObject"></param>
            /// <param name="__instance"></param>
            public static void addItemToInventoryBool_Prefix(Item item, bool makeActiveObject, Farmer __instance)
            {
                try
                {
                    if (__instance.IsLocalPlayer && item != null) //if this farmer is the local player and the item isn't null
                    {
                        if (!(Game1.activeClickableMenu is GeodeMenu)) //if the active menu is NOT a geode menu (which already handles this process)
                        {
                            Utility.Monitor.Log($"TEST: GeodeMenu allegedly isn't open right now. Checking mineral stuff.", LogLevel.Alert);
                            if (!item.HasBeenInInventory && item is StardewValley.Object obj && !obj.HasBeenPickedUpByFarmer) //if this item is an object that has NOT been picked up before
                            {
                                if (obj.Category == -12) //if this object is in the "minerals" category
                                {
                                    __instance.foundMineral(obj.ParentSheetIndex); //add this mineral to the player's collection
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Utility.Monitor.Log($"A Harmony patch encountered an error. Minerals spawned by this mod might not be added to your collection when picked up.", LogLevel.Warn);
                    Utility.Monitor.Log($"The auto-generated error message is displayed below:", LogLevel.Warn);
                    Utility.Monitor.Log($"----------", LogLevel.Warn);
                    Utility.Monitor.Log($"{ex.ToString()}", LogLevel.Warn);
                }
            }
        }
    }
}
